include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for babeld
LUCI_DEPENDS:=+babeld +luci-compat +luci-theme-argon
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
