#
# This is free software, lisence use MIT.
# 
# 
#

name: Merge-kenzo
on:
  push:
    paths:
      - '.github/workflows/kenzo.yml'
      - '.gitignore'
      - 'diy/**'
  schedule:
    - cron: 0 */11 * * *
  workflow_dispatch:
    inputs:
      ssh:
        description: 'ssh'
        required: false
        default: 'true'
  watch:
    types: started
  repository_dispatch:

jobs:
  merge:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Syn kenzo
      run: |
        shopt -s extglob
        git rm -r --cache * >/dev/null 2>&1 &
        rm -rf `find ./* -maxdepth 0 -type d ! -name "diy"` >/dev/null 2>&1
        function git_clone() (
          git clone --depth 1 $1 $2 || true
        )
        function git_sparse_clone() (
          branch="$1" rurl="$2" localdir="$3" && shift 3
          git clone -b $branch --depth 1 --filter=blob:none --sparse $rurl $localdir
          cd $localdir
          git sparse-checkout init --cone
          git sparse-checkout set $@
          mv -n $@ ../
          cd ..
          rm -rf $localdir
          )
        function mvdir() {
        mv -n `find $1/* -maxdepth 0 -type d` ./
        rm -rf $1
        }
        (
        git_clone https://github.com/kiddin9/my-packages && mvdir my-packages
        git_clone https://github.com/kiddin9/openwrt-bypass && mvdir openwrt-bypass
        git_clone https://github.com/kiddin9/luci-app-dnsfilter
        git_clone https://github.com/kiddin9/aria2
        git_clone https://github.com/kiddin9/luci-app-baidupcs-web
        git_clone https://github.com/kiddin9/luci-theme-edge
        git_clone https://github.com/kiddin9/qBittorrent-Enhanced-Edition
        git_clone https://github.com/kiddin9/autoshare && mvdir autoshare
        git_clone https://github.com/kiddin9/openwrt-openvpn && mvdir openwrt-openvpn
        git_clone https://github.com/kiddin9/luci-app-xlnetacc
        git_clone https://github.com/kiddin9/openwrt-amule-dlp && mvdir openwrt-amule-dlp
        git_clone https://github.com/kiddin9/luci-app-wizard
        ) &
        (
        git_clone https://github.com/xiaorouji/openwrt-passwall
        git_clone https://github.com/xiaorouji/openwrt-passwall2 passwall2 && mv -n passwall2/luci-app-passwall2 ./;rm -rf passwall2
        git_clone -b luci https://github.com/xiaorouji/openwrt-passwall passwall1 && mv -n passwall1/luci-app-passwall  ./; rm -rf passwall1		
        git_clone https://github.com/Lienol/openwrt-package
        git_clone https://github.com/ysc3839/openwrt-minieap
        git_clone https://github.com/ysc3839/luci-proto-minieap
        git_clone https://github.com/rufengsuixing/luci-app-autoipsetadder
        git_clone https://github.com/rufengsuixing/luci-app-onliner
        git_clone https://github.com/rufengsuixing/luci-app-usb3disable			
        git_clone https://github.com/NateLol/luci-app-beardropper
        git_clone https://github.com/NateLol/luci-app-oled		
        git_clone https://github.com/riverscn/openwrt-iptvhelper && mvdir openwrt-iptvhelper
        git_clone https://github.com/iwrt/luci-app-ikoolproxy  && mv -f luci-app-ikoolproxy/ikoolproxy ikoolproxy
        git_clone https://github.com/BoringCat/luci-app-minieap	
        git_clone https://github.com/tty228/luci-app-serverchan
        git_clone https://github.com/4IceG/luci-app-sms-tool smstool && mvdir smstool
        git_clone https://github.com/silime/luci-app-xunlei
        
        ) &
        (
        git_clone https://github.com/zzsj0928/luci-app-pushbot
        git_clone https://github.com/shanglanxin/luci-app-homebridge
        git_clone https://github.com/jerrykuku/luci-theme-argon
        git_clone https://github.com/jerrykuku/luci-app-argon-config
        git_clone https://github.com/jerrykuku/luci-app-vssr
        git_clone https://github.com/jerrykuku/luci-app-ttnode
        git_clone https://github.com/jerrykuku/luci-app-jd-dailybonus
        git_clone https://github.com/jerrykuku/luci-app-go-aliyundrive-webdav		
        git_clone https://github.com/peter-tank/luci-app-dnscrypt-proxy2
        git_clone https://github.com/sirpdboy/luci-app-advanced
        git_clone https://github.com/sirpdboy/luci-app-netdata
        git_clone https://github.com/sirpdboy/luci-app-autotimeset
        git_clone https://github.com/sirpdboy/netspeedtest && mv -n netspeedtest/luci-app-netspeedtest ./ ; rm -rf netspeedtest		
        git_clone https://github.com/wolandmaster/luci-app-rtorrent
        git_clone https://github.com/lloyd18/luci-app-npc
        ) &
        (
        git_clone https://github.com/destan19/OpenAppFilter && mvdir OpenAppFilter
        git_clone https://github.com/esirplayground/luci-app-poweroff
        git_clone https://github.com/esirplayground/LingTiGameAcc
        git_clone https://github.com/esirplayground/luci-app-LingTiGameAcc		
        git_clone https://github.com/lvqier/luci-app-dnsmasq-ipset
        git_clone https://github.com/walkingsky/luci-wifidog luci-app-wifidog
        git_clone https://github.com/peter-tank/luci-app-autorepeater
        git_clone https://github.com/CCnut/feed-netkeeper && mvdir feed-netkeeper
        git_clone https://github.com/brvphoenix/luci-app-wrtbwmon wrtbwmon1 && mvdir wrtbwmon1
        git_clone https://github.com/brvphoenix/wrtbwmon wrtbwmon2 && mvdir wrtbwmon2
        git_clone https://github.com/sensec/luci-app-udp2raw
        git_clone https://github.com/LGA1150/openwrt-sysuh3c && mvdir openwrt-sysuh3c
        git_clone https://github.com/gdck/luci-app-cupsd cupsd1 && mv -n cupsd1/luci-app-cupsd cupsd1/cups/cups ./ ; rm -rf cupsd1
        git_clone https://github.com/QiuSimons/openwrt-mos && mv -n openwrt-mos/*mosdns ./ ; rm -rf openwrt-mos
        git_clone https://github.com/sundaqiang/openwrt-packages && mv -n openwrt-packages/luci-* ./; rm -rf openwrt-packages
        ) &
        (
        git_clone https://github.com/zxlhhyccc/luci-app-v2raya
	git clone -b 21.02 https://github.com/kenzok78/luci-theme-argonne
	git clone https://github.com/kenzok78/luci-app-argonne-config
	git_clone https://github.com/thinktip/luci-theme-neobird
        git_clone https://github.com/Tencent-Cloud-Plugins/tencentcloud-openwrt-plugin-ddns && mv -n tencentcloud-openwrt-plugin-ddns/tencentcloud_ddns ./luci-app-tencentddns; rm -rf tencentcloud-openwrt-plugin-ddns
        git_clone https://github.com/Tencent-Cloud-Plugins/tencentcloud-openwrt-plugin-cos && mv -n tencentcloud-openwrt-plugin-cos/tencentcloud_cos ./luci-app-tencentcloud-cos; rm -rf tencentcloud-openwrt-plugin-cos
        git_clone https://github.com/doushang/luci-app-shortcutmenu luci-shortcutmenu && mv -n luci-shortcutmenu/luci-app-shortcutmenu ./ ; rm -rf luci-shortcutmenu
        git_clone https://github.com/sbilly/netmaker-openwrt && mv -n netmaker-openwrt/netmaker ./; rm -rf netmaker-openwrt
        git_clone https://github.com/lisaac/luci-app-dockerman dockerman && mv -n dockerman/applications/* ./; rm -rf dockerman
        ) &
        (
        git_clone https://github.com/messense/aliyundrive-webdav aliyundrive && mv -n aliyundrive/openwrt/* ./ ; rm -rf aliyundrive
        git_clone https://github.com/messense/aliyundrive-fuse aliyundrive && mv -n aliyundrive/openwrt/* ./;rm -rf aliyundrive	
        git_clone https://github.com/messense/openwrt-wiretrustee && mv -n openwrt-wiretrustee/wiretrustee ./;rm -rf openwrt-wiretrustee
        git_clone https://github.com/ophub/luci-app-amlogic amlogic && mv -n amlogic/luci-app-amlogic amlogic/depends/* ./;rm -rf amlogic
        git_clone https://github.com/mingxiaoyu/luci-app-cloudflarespeedtest cloudflarespeedtest && mv -n cloudflarespeedtest/applications/* ./;rm -rf cloudflarespeedtest
        git_clone https://github.com/linkease/nas-packages && mv -n nas-packages/network/services/* ./; rm -rf nas-packages
        git_clone https://github.com/linkease/nas-packages-luci && mv -n nas-packages-luci/luci/* ./; rm -rf nas-packages-luci
        git_clone https://github.com/linkease/luci-app-linkease
        git clone -b lede https://github.com/pymumu/luci-app-smartdns		
        ) &
        (
        svn export https://github.com/x-wrt/packages/trunk/net/nft-qos
        svn export https://github.com/x-wrt/luci/trunk/applications/luci-app-nft-qos
        svn export https://github.com/x-wrt/com.x-wrt/trunk/luci-app-macvlan
        svn export https://github.com/Ysurac/openmptcprouter-feeds/trunk/luci-app-iperf
        svn export https://github.com/fw876/helloworld/trunk/luci-app-ssr-plus
        svn export https://github.com/vernesong/OpenClash/trunk/luci-app-openclash
	svn export https://github.com/Carseason/openwrt-themedog/trunk/luci/luci-themedog
        ) &
        (
        git_sparse_clone openwrt-21.02 "https://github.com/openwrt/packages" "oppackages" \
        net/openvpn utils/cgroupfs-mount utils/coremark net/xray-core net/nginx net/uwsgi net/ddns-scripts admin/netdata
        git_sparse_clone openwrt-21.02 "https://github.com/openwrt/openwrt" "openwrt" \
        package/base-files package/network/config/firewall package/system/opkg package/libs/mbedtls package/network/services/ppp package/network/services/dnsmasq
        git_sparse_clone openwrt-21.02 "https://github.com/openwrt/luci" "opluci" applications/luci-app-attendedsysupgrade applications/luci-app-aria2 \
        applications/luci-app-ddns applications/luci-app-acme applications/luci-app-transmission applications/luci-app-opkg applications/luci-app-firewall \
        applications/luci-app-ksmbd applications/luci-app-samba4 modules/luci-base modules/luci-mod-network \
        modules/luci-mod-status modules/luci-mod-system
        ) &
        (
        git_sparse_clone master "https://github.com/immortalwrt/packages" "immpkgs" net/adguardhome net/mwol \
        net/sub-web net/smartdns net/dnsproxy net/haproxy net/v2raya net/cdnspeedtest \
        net/subconverter net/ngrokc net/oscam net/njitclient net/scutclient net/gost net/gowebdav \
        admin/bpytop libs/jpcre2 libs/wxbase libs/rapidjson libs/libcron libs/quickjspp libs/toml11 \
        utils/cpulimit utils/filebrowser
        git_sparse_clone master "https://github.com/xiaoqingfengATGH/feeds-xiaoqingfeng" "xiaoqingfeng" homeredirect luci-app-homeredirect
        ) &
        (
        git_sparse_clone master "https://github.com/coolsnowwolf/packages" "leanpkg" net/miniupnpd net/mwan3 multimedia/UnblockNeteaseMusic-Go \
        multimedia/UnblockNeteaseMusic net/amule net/baidupcs-web net/frp multimedia/gmediarender net/go-aliyundrive-webdav \
        net/qBittorrent-static net/qBittorrent libs/qtbase libs/qttools libs/rblibtorrent \
        net/uugamebooster net/verysync net/vlmcsd net/dnsforwarder net/nps net/tcpping net/redsocks2
        git_sparse_clone develop "https://github.com/Ysurac/openmptcprouter-feeds" "openmptcp" luci-app-snmpd \
        luci-app-packet-capture luci-app-mail msmtp
        ) &

        svn export --force https://github.com/coolsnowwolf/luci/trunk/applications
        rm -rf applications/luci-app-qbittorrent
        svn co https://github.com/immortalwrt/luci/trunk/applications

        for ipk in $(ls -d applications/!(luci-app-rclone)/); do
        	if [[ $(ls $ipk/po | wc -l) -gt 3 ]]; then
            rm -rf $ipk
        	fi
        done

        git_sparse_clone master "https://github.com/coolsnowwolf/lede" "leanlede" package/lean package/kernel/rtl8821cu package/network/services/shellsync package/network/utils/dpdk

    - name: Delete duplicated packages
      run: |
        shopt -s extglob
        mv -n openwrt-passwall/* ./ ; rm -Rf openwrt-passwall
        mv -n applications/!(luci-app-noddos|luci-app-cshark|luci-app-dnscrypt-proxy|luci-app-https-dns-proxy) ./ ; rm -Rf applications
        mv -n lean/* ./ ; rm -Rf lean
        mv -n openwrt-package/* ./ ; rm -Rf openwrt-package
        cp -rf diy/.packages/* ./ || true
        rm -Rf */.git

    - name: SSH connection to Actions
      uses: kenzok78/debugger-action@master
      if: github.event.inputs.ssh == 'true'

    - name: Apply patches
      run: |
        find "diy/patches" -type f -name '*.patch' -print0 | sort -z | xargs -I % -t -0 -n 1 sh -c "cat '%'  | patch -d './' -p1 -E --forward --no-backup-if-mismatch"

    - name: Modify
      run: |
        shopt -s extglob
        sed -i \
        -e "s/\(network\..*\)\.ifname/\1.device/g" \
        `find \( -path "*/root/*" -o -path "*/files/*" -o -path "*/luasrc/*" \) ! -path "./base-files/*" ! -path "./dnsmasq/*" ! -path "./luci-base/*" ! -path "./ppp/*" -type f` &
        (
        function latest() {
          (curl -gs -H 'Content-Type: application/json' \
             -H "Authorization: Bearer ${{ secrets.REPO_TOKEN }}" \
             -X POST -d '{ "query": "query {repository(owner: \"'"$1"'\", name: \"'"$2"'\"){refs(refPrefix:\"refs/tags/\",last:1,orderBy:{field:TAG_COMMIT_DATE,direction:ASC}){edges{node{name target{commitUrl}}}}defaultBranchRef{target{...on Commit {oid}}}}}"}' https://api.github.com/graphql)
        }
        for pkg in $(ls !(luci-*|natflow|ps3netsrv|rblibtorrent|shadowsocksr-libev|v2ray-core|n2n_v2|mosdns|coremark|mbedtls|rtl8821cu|rtl8188eu|rtl8812au-ac|quickjspp|libcups|netdata)/Makefile); do
          repo="$(grep PKG_SOURCE_URL $pkg | grep github | cut -f 4-5 -d '/' | sed -e 's/.git//' | grep -E '[0-9a-zA-Z_-]+$')" || true
          if [ "$repo" ]; then
            owner="$(echo $repo | cut -f 1 -d '/')"
            name="$(echo $repo | cut -f 2 -d '/')"
            latest="$(latest $owner $name)"
            sed -i "s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=$(echo $latest | jq -r '.data.repository.defaultBranchRef.target.oid')/" $pkg || true
            over="$(grep -E PKG_VERSION:=.*$ $pkg | cut -f 2 -d '=' | sed -e 's/^\(v\|release-\)//' | grep -E "[0-9]")" || true
            if [ "$over" ]; then
              ver="$(echo $latest | jq -r '.data.repository.refs.edges[-1].node.name' | sed -e 's/^\(v\|release-\)//' | grep -E "^[^()]*$" | grep -E "[0-9]")" || true
              # [ "$ver" ] || ver="$(git ls-remote --tags git://github.com/$repo | cut -d/ -f3- | sort -t. -nk1,3 | awk '/^[^{]*$/{version=$1}END{print version}' | grep -o -E "[0-9].*")" || true
              echo "$repo-$over-$ver"
              if [ "$ver" ]; then
                function version_lt() { test "$(echo "$@" | tr " " "\n" | sort -rV | head -n 1)" != "$1"; }
                if version_lt "$over" "$ver"; then
                  sed -i -e "s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=$(echo $latest | jq -r '.data.repository.refs.edges[-1].node.target.commitUrl' | cut -f 7 -d /)/" \
                         -e "s/PKG_VERSION:=.*/PKG_VERSION:=$ver/" $pkg || true
                fi || true
              fi
            fi
          fi
        done
        touch /tmp/ok
        ) &
        
        for pkg in $(find -maxdepth 1 -type d -name "luci-*" ! -name "luci-app-dockerman" ! -name "luci-app-frpc" ! -name "luci-app-frps"); do
          grep -q '"nas",' $pkg/luasrc/controller/*.lua && ! grep -q '_("NAS")' $pkg/luasrc/controller/*.lua &&
            sed -i 's/index()/index()\n\tentry({"admin", "nas"}, firstchild(), _("NAS") , 45).dependent = false/' $pkg/luasrc/controller/*.lua
        done
        (
        touch /tmp/ok2
        ) &
        sed -i 's/luci-lib-ipkg/luci-base/g' luci-app-store/Makefile
        bash diy/create_acl_for_luci.sh -a >/dev/null 2>&1 || true
        bash diy/convert_translation.sh -a >/dev/null 2>&1 || true
        
        #sed -i 's?"http://" + window.location.hostname?window.location.protocol + "//" + window.location.hostname?g' `find luci-app*/luasrc/view/ -maxdepth 2 -name "*.htm"`
        rm -f miniupnpd/patches/106-spam-syslog*
        sed -i "/minisign:minisign/d" luci-app-dnscrypt-proxy2/Makefile
        sed -i 's/+libstdcpp/+libstdcpp +zlib/' ngrokc/Makefile
        sed -i 's/+dockerd/+dockerd +cgroupfs-mount/' luci-app-docker*/Makefile
        sed -i '$i /etc/init.d/dockerd restart &' luci-app-docker*/root/etc/uci-defaults/*
        sed -i 's/+rclone\( \|$\)/+rclone +fuse-utils\1/g' luci-app-rclone/Makefile
        sed -i 's/+libcap /+libcap +libcap-bin /' luci-app-openclash/Makefile
        sed -i 's/\(+luci-compat\)/\1 +luci-theme-argon/' luci-app-argon-config/Makefile
        sed -i 's/+vsftpd$/+vsftpd-alt/' luci-app-vsftpd/Makefile
        sed -i 's/ +uhttpd-mod-ubus//' luci-app-packet-capture/Makefile
        sed -i '/boot()/,+2d' ddns-scripts/files/etc/init.d/ddns
        sed -i "/DISTRIB_DESCRIPTION/c\DISTRIB_DESCRIPTION=\"%D %C by kenzo'\"" base-files/files/etc/openwrt_release
        sed -i 's?admin/status/channel_analysis??' luci-mod-status/root/usr/share/luci/menu.d/luci-mod-status.json
        sed -i "/--disable-https/d" netdata/Makefile
        sed -i -e '$a /etc/bench.log' \
        -e '/\/etc\/profile/d' \
        -e '/\/etc\/shinit/d' \
        base-files/files/lib/upgrade/keep.d/base-files-essential
        sed -i -e '/^\/etc\/profile/d' \
        -e '/^\/etc\/shinit/d' \
        base-files/Makefile
        sed -i '$a cgi-timeout = 300' uwsgi/files-luci-support/luci-webui.ini
        sed -i '$a cgi-timeout = 60' uwsgi/files-luci-support/luci-cgi_io.ini
        sed -i '/limit-as/c\limit-as = 5000' uwsgi/files-luci-support/luci-webui.ini
        sed -i 's/procd_set_param stderr 1/procd_set_param stderr 0/' uwsgi/files/uwsgi.init
        cp -rf base-files/files/sbin/sysupgrade my-default-settings/files/sbin/
        
        sed -i \
          -e 's?include \.\./\.\./\(lang\|devel\)?include $(TOPDIR)/feeds/packages/\1?' \
          -e "s/\(PKG_HASH\|PKG_MD5SUM\|PKG_MIRROR_HASH\):=.*/\1:=skip/" \
          -e 's?\.\./\.\./luci.mk?$(TOPDIR)/feeds/luci/luci.mk?' \
          -e 's/ca-certificates/ca-bundle/' \
          */Makefile
        
        while [[ ! -f /tmp/ok ]]; do
            echo "wait"
          sleep 1
        done
        
        rm -rf create_acl_for_luci.warn && rm -rf create_acl_for_luci.ok
        rm -rf create_acl_for_luci.err

    - name: Apply
      run: |
        git add .
        git commit -m "update $(date +%m-%d" "%H:%M:%S)"
        git reset --soft HEAD^
        git add .
        git commit -m "update $(date +%m-%d" "%H:%M:%S)"
        git push -f

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 1



